### ISSUE TITLE
Error in Rails for Quickstart: uninitialized constant OpenCensus::Trace::Integrations::RackMiddleware

### ISSUE THREAD

**Issue by bshaffer** [census-instrumentation/opencensus-ruby#49]
Getting the following error when following the [quickstart](https://github.com/census-instrumentation/opencensus-ruby#getting-started-with-ruby-on-rails) for both `rails` and `rack_middleware`:
```
/usr/local/lib/ruby/gems/2.3.0/gems/opencensus-0.2.0/lib/opencensus/trace/integrations/rack_middleware.rb:40:in `<class:RackMiddleware>': uninitialized constant OpenCensus::Trace::Integrations::RackMiddleware::Formatters (NameError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/opencensus-0.2.0/lib/opencensus/trace/integrations/rack_middleware.rb:32:in `<module:Integrations>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/opencensus-0.2.0/lib/opencensus/trace/integrations/rack_middleware.rb:17:in `<module:Trace>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/opencensus-0.2.0/lib/opencensus/trace/integrations/rack_middleware.rb:16:in `<module:OpenCensus>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/opencensus-0.2.0/lib/opencensus/trace/integrations/rack_middleware.rb:15:in `<top (required)>'
    from /Library/WebServer/Code/trace-against-the-clock/blog-rails/config/application.rb:6:in `require'
    from /Library/WebServer/Code/trace-against-the-clock/blog-rails/config/application.rb:6:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `block in perform'
    from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
    from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
    from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
    from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
    from /Library/WebServer/Code/trace-against-the-clock/blog-rails/bin/rails:9:in `require'
    from /Library/WebServer/Code/trace-against-the-clock/blog-rails/bin/rails:9:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
    from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
    from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from bin/spring:15:in `<top (required)>'
    from bin/rails:3:in `load'
```

The formatters actually reside in the module `OpenCensus::Trace::Formatters`, but manually changing the loaded namespace still throws an error. Any idea what I'm doing wrong?? Thanks!

**Comment by dazuma** [comment]
@bshaffer  For now, do this:

```ruby
require "opencensus"  # Insert this first before:
require "opencensus/trace/integrations/rails"
```

I'll fix the code so this isn't necessary.
